apiVersion: v1
kind: Service
metadata:
  name: log-analyzer-service
  namespace: app-log-analyzer 
spec:
  selector:
    app: log-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort